---
- hosts: localhost
  connection: local
  vars:
    - namespace: "{{ lookup('env', 'NAMESPACE') | default('default', true) }}"
    - cluster_name: "{{ lookup('env', 'CLUSTER_NAME') | default('mongo', true) }}"
    - cluster_dns_suffix: "cluster.local"
  tasks:
    - name: Generate certificate authority
      shell: "cfssl genkey -initca files/ca-csr.json | cfssljson -bare /tmp/ca"

    - name: Generate admin credentials
      set_fact: admin_credentials="{{ lookup('password', '/tmp/admin-password.txt length=32 chars=ascii_letters,digits') }}"

    - name: Generate monitoring credentials
      set_fact: monitoring_credentials="{{ lookup('password', '/tmp/monitoring-password.txt length=32 chars=ascii_letters,digits') }}"

    - name: Get k8s service account token
      set_fact: k8s_token="{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"

    - name: Create certificate authority secret
      shell: "kubectl \
        -s https://kubernetes \
        --certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
        --token {{ k8s_token }} \
        --namespace={{ namespace }} \
        create secret generic {{ cluster_name }}-ca \
          --from-file=ca.pem=/tmp/ca.pem \
          --from-file=ca-key.pem=/tmp/ca-key.pem \
          --from-file=ca.csr=/tmp/ca.csr"

    - name: Create admin credentials secret
      shell: "kubectl \
        -s https://kubernetes \
        --certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
        --token {{ k8s_token }} \
        --namespace={{ namespace }} \
        create secret generic {{ cluster_name }}-admin-credentials \
          --from-literal=username=root \
          --from-literal=password={{ admin_credentials }}"

    - name: Create monitoring credentials secret
      shell: "kubectl \
        -s https://kubernetes \
        --certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
        --token {{ k8s_token }} \
        --namespace={{ namespace }} \
        create secret generic {{ cluster_name }}-monitoring-credentials \
          --from-literal=username=monitoring \
          --from-literal=password={{ monitoring_credentials }}"
