---
- hosts: localhost
  connection: local
  vars:
    - namespace: "{{ lookup('env', 'NAMESPACE') }}"
    - cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    - k8s_token: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
  tasks:
    - name: Generate certificate authority
      shell: "cfssl genkey -initca files/ca-csr.json | cfssljson -bare /tmp/ca"

    - name: Generate admin password
      set_fact: admin_credentials="{{ lookup('password', '/tmp/admin-password.txt length=32 chars=ascii_letters,digits') }}"

    - name: Create certificate authority secret
      shell: "kubectl \
        -s https://kubernetes \
        --certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
        --token {{ k8s_token }} \
        --namespace={{ namespace }} \
        create secret generic {{ cluster_name }}-ca \
          --from-file=ca.pem=/tmp/ca.pem \
          --from-file=ca-key.pem=/tmp/ca-key.pem \
          --from-file=ca.csr=/tmp/ca.csr"

    - name: Create admin credentials secret
      shell: "kubectl \
        -s https://kubernetes \
        --certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
        --token {{ k8s_token }} \
        --namespace={{ namespace }} \
        create secret generic {{ cluster_name }}-admin-credentials \
          --from-literal=username=root \
          --from-literal=password={{ admin_credentials }}"
